[package]
name = "nanotubes"
description = "Fancy websocket wrapper"
license = "Apache-2.0"
version = "0.1.0"
edition = "2021"

[dependencies]
async-tungstenite = "0.16.1"
uuid = "0.8.2"
retry = "1.3.0"
thiserror = "1.0.30"
miette = "3.2.0"
dashmap = "5.0.0"
